vars: {
  d2-config: {
    sketch: true
    layout-engine: elk
    theme-id: 300
  }
}
direction: left

classes: {
  happy: {
    style {
      stroke: green
      stroke-width: 4
    }
  }
  sad: {
    style {
      stroke: red
      stroke-width: 4
    }
  }
}

StateMachine: {
  direction: left
  label: "Charger State Machine"

  Preparing: {
    style: {fill: lightyellow}
      icon: "./images/inserted_unlocked.png"
  }

  Authorizing: {
    style: {fill: orange}
    icon: "./images/inserted_unlocked.png"
  }

  StartTransaction {
    style: {fill: lightblue}
  }

  StopTransaction {
    style: {fill: lightcoral}
  }

  Charging: {
    style: {fill: lightblue}
    icon: "./images/lock+charging.png"
  }

  All States {}

  Faulted: {
    style: {fill: pink}
      icon: "./images/unlock_wide.png"
  }
  Available: {
    style: {fill: lightgreen}
      icon: "./images/unlock_nocable.png"
  }



  All States -> Faulted: Error occured {class: sad}
  Available -> Preparing: Cable Inserted {class: happy}
  Preparing -> Available: Cable Removed {class: happy}
  Preparing -> Authorizing: Card Swiped {class: happy}
  Authorizing -> StartTransaction: Authorization Accepted {class: happy}
  StartTransaction -> Charging: Transaction Accepted {class: happy}
  StartTransaction -> Preparing: Transaction Rejected {class: sad}
  Authorizing -> Preparing: Authorization Rejected {class: sad}
  Charging -> StopTransaction: Card Swiped {class: happy}
  StopTransaction -> Charging: Transaction Rejected {class: sad}
  StopTransaction -> Preparing: Transaction Accepted {class: happy}
  Faulted -> Available: Charger Resetted {class: happy}
}
